  # df This workflow will install Python dependencies, run tests and lint widsth a single version of Python
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
  
  name: Python application
  
  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
  permissions:
    contents: read
  
  jobs:
    build:
  
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build and push image
        run: |
          docker login --username lohithsurya --password ${{secrets.GH_PAT}} ghcr.io
          docker build . -tag ghcr.io/lohithsurya/movieimage:latest
          docker push ghcr.io/lohithsurya/movieimage:latest
        
